name: rasusa-vircov
channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - snakemake
  - python
  - biopython=1.78
  - pip:
    - rich
  - r-optparse
  - r-ggplot2
  - r-stringr
  - r-dplyr
  - r-tidyr
  - r-patchwork
  - r-furrr
